### ISSUE TITLE
如何计算模型的长宽高  表面积  体积？

### ISSUE THREAD

**Issue by Guoxiaotang** [hujiulong/vue-3d-model#105]
模型上传后，哪里能得到模型的参数信息？比如长宽高，表面积，体积等信息

**Comment by hujiulong** [comment]
没办法得到这些信息。
如果模型是几根线条，那么它的表面积和体积是什么？
如果模型是一个没有底的圆柱，那么它的体积是什么？
另外怎么定义表面积？如果一个模型破了一个洞，那它内部的面积算不算表面积？
