### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Guoxiaotang** [hujiulong/vue-3d-model#108]
我下载代码后执行编译的时候，报了下面的错，这个是什么原因呢？
[!] Error: 'default' is not exported by node_modules\_vue-runtime-helpers@1.0.0@vue-runtime-helpers\dist\normalize-component.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
src\model-obj.vue (17:7)
15:             type: Array,
16:             default() {
17:                 return [
           ^
18:                     {
19:                         type: 'HemisphereLight',

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-3d-model@1.0.2 build: `rollup -c build/rollup.prod.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-3d-model@1.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by hujiulong** [comment]
给一个可以复现问题的最简代码仓库

**Comment by Guoxiaotang** [comment]
https://github.com/hujiulong/vue-3d-model.git  我直接下载你的代码，然后执行的npm install   在执行package.json中的   "build": "rollup -c build/rollup.prod.conf.js"  就会出现这个问题

**Comment by Guoxiaotang** [comment]
我查了这个错误，  是由与依赖中存在一些非 es6 module的代码  rollup要配置commonjs来处理，我已经配置了  const plugins = [
    nodeResolve(),
    vue(),
    babel( {
        exclude: 'node_modules/**'
    } ),
    resol( {
        jsnext: true,
        main: true,
        browser: true,
    } ),
    commonjs()
]
现在不报之前的错，但是build的时候  会缺失很多的包，我install了十几个了 还是没完，我看缺失的有些是vue的基本包

**Comment by hujiulong** [comment]
好的，我复现这个问题了，是因为rollup-plugin-vue更新导致的。我晚点整个更新一下构建工程。

**Comment by Guoxiaotang** [comment]
好的，辛苦辛苦

**Comment by hujiulong** [comment]
已经修复了
