### ISSUE TITLE
Lighting Question

### ISSUE THREAD

**Issue by btbritz** [hujiulong/vue-3d-model#11]
I'm trying to light the entire model equally(obj + mtl), so that there aren't any shadows when the model is rendered. Is this something I can do as a property? I noticed you have a "lights" prop in the readme but I'm not sure how to use it.

**Comment by hujiulong** [comment]
shadow is not supported yet, but I plan to add this feature.

**Comment by btbritz** [comment]
I should have mentioned that a good fix for this was to just add another hem light to the light props with a bit of a higher intensity.
