### ISSUE TITLE
ModelSTL component does not display anything

### ISSUE THREAD

**Issue by gggggbbbbb** [hujiulong/vue-3d-model#110]
I am trying to implement the ModelSTL component using one the example provided. The code is reported here below:

```
<template>
    <model-stl src="static/models/stl/slotted_disk.stl"></model-stl>
</template>

<script>
    import { ModelStl } from 'vue-3d-model'

    export default {
        components: {
            ModelStl
        }
    }
</script>
```
If I run the example from the repo, everything works fine. When I try to implement in my project (created with CLI 3), the component seems to load but does not display anything (empty div). What am I missing? Thanks!

**Comment by hujiulong** [comment]
Is there any error message in the console?

**Comment by gggggbbbbb** [comment]
No error in console, component seems to load correctly (please see image). I am trying to load the same .stl file provided in the examples.

![ModelSTL](https://user-images.githubusercontent.com/18688158/60415278-fb220f80-9bda-11e9-8346-317081fc185a.png)

**Comment by hujiulong** [comment]
Can you upload your project to github?

**Comment by gggggbbbbb** [comment]
I have uploaded it here: https://github.com/gggggbbbbb/3d-test

**Comment by hujiulong** [comment]
https://github.com/hujiulong/vue-3d-model/issues/74#issuecomment-455884667

**Comment by gggggbbbbb** [comment]
Great, thank you!

**Comment by gggggbbbbb** [comment]
I have encountered a weird behaviour: if I integrate the component as part of a modal window, it only shows up after I resize the browser window. This is probably more related to how Vue works, but do you have any suggestion on how to fix this?

**Comment by hujiulong** [comment]
@gggggbbbbb https://github.com/hujiulong/vue-3d-model/issues/52
