### ISSUE TITLE
Thumbnail/Snapshot Creation

### ISSUE THREAD

**Issue by gggggbbbbb** [hujiulong/vue-3d-model#111]
Do you think it is possible to automatically create a thumbnail from the scene? It would be really useful for many applications!

**Comment by joaquinco** [comment]
Hey, you can easily take a snapshot like this:

```javascript
    takeSnapshot() {
      let { renderer } = this.modelRef;
      return renderer.domElement.toDataURL("image/png", 1);
    }
```
where `this.modelRef` is the model loader instance, for example `ModelObj`.

**Comment by gggggbbbbb** [comment]
Thank you @joaquinco! What I am trying to achieve is to generate the snapshot immediately (and save it for reference) after the asset is uploaded by the user and even before being displayed in the viewer. Do you think it is possible with the method you suggested?

**Comment by gggggbbbbb** [comment]
Hello, I was wondering if anyone can point me towards the right direction to achieve what described in my previous message, thanks!

**Comment by joaquinco** [comment]
Hi, sorry I've been offline lately. You can create a wrapper component of the model loader where you would put the function I told you previously and call it on the on-load event of the model loader.

You should probably wait some time to let the actual tender happening. So calling the takeSnapshot function in a timeout of a few undred milisecs should be fine. 

I don't have the time to give you a more complete solution but you should be one track with this.

**Comment by gggggbbbbb** [comment]
Hey @joaquinco, thank you! I am actually a step behind that stage as I am still trying to get a screenshot of the STL viewer. While the takeSnapshot function you mentioned above is able to generate an image, it appears empty (the model is not there) once visualised in a new tab. I have recreated an isolated example of the issue here: https://github.com/gggggbbbbb/3d-test . Is there something that I am missing?

**Comment by rokumatsumoto** [comment]
I didn't test it but can you try like this? @gggggbbbbb 

> You can create a wrapper component of the model loader where you would put the function I told you previously and call it on the on-load event of the model loader.

> So calling the takeSnapshot function in a timeout of a few undred milisecs should be fine.

```html
<template>
    <div style="height: 550px" class="view" >
      <model-stl @on-load="onLoad" ref="model" src="/static/models/gear.stl"></model-stl>
    <button v-if="isLoaded" @click="setTimeout(this.takeSnap, 100)">Snapshot</button>
    </div>    
</template>
```
``` javascript
<script>
import ModelStl  from 'vue-3d-model/src/model-stl.vue'
export default {
  components: {
    ModelStl
  } ,
  data() {
    return {
      isLoaded: false,
    };
  },
  },
  methods:{
    onLoad () {
      this.isLoaded = true;
    },
    takeSnap(){
      let {renderer}  = this.$refs.model;
      let image =  renderer.domElement.toDataURL("image/png");
      window.open(image); 
    }
  }
}
</script>
```

**Comment by gggggbbbbb** [comment]
Hey @rokumatsumoto, it doesn't seem to work (setTimeout is not defined on the instance...), I changed it to the code below and while it generates an image, this is still empty:

```
<template>
    <div style="height: 550px" class="view" >
      <model-stl @on-load="onLoad" ref="model" src="/static/models/gear.stl"></model-stl>
    <button v-if="isLoaded" @click="snap">Snapshot</button>
    </div>    
</template>

<script>
import ModelStl  from 'vue-3d-model/src/model-stl.vue'
export default {
  components: {
    ModelStl
  } ,
  data() {
    return {
      isLoaded: false,
    }
  },

  methods:{
    onLoad () {
      this.isLoaded = true;
    },
    takeSnap(){
      let {renderer}  = this.$refs.model;
      let image =  renderer.domElement.toDataURL("image/png");
      window.open(image); 
    },
    snap: function () {
    setTimeout( this.takeSnap() , 2000)
},
  }
}
</script>
```

**Comment by joaquinco** [comment]
The timeout was only needed if you take the snapshot onload.

If the image is empty you have to check firts if the model loader loads the model and focuses it correctly.

**Comment by gggggbbbbb** [comment]
Hey @joaquinco, thanks for the insight! Below you can find the most basic version of the code (click button, open a new tab with the screenshot). The model is loaded correctly and displayed, the image is generated but it is empty.  Could you have a look at the code (repo here: https://github.com/gggggbbbbb/3d-test) and check whether you see something wrong with it? Thanks!

```
<template>
    <div style="height: 550px" class="view" >
      <model-stl  ref="model" src="/static/models/gear.stl"></model-stl>
    <button @click="takeSnap">Snapshot</button>
    </div>    
</template>

<script>
import ModelStl  from 'vue-3d-model/src/model-stl.vue'
export default {
  components: {
    ModelStl
  } ,
  data() {
    return {

    }
  },

  methods:{
     takeSnap(){
      let {renderer}  = this.$refs.model;
      let image =  renderer.domElement.toDataURL("image/png");
      window.open(image); 
    },
  }
}
</script>
```

**Comment by rokumatsumoto** [comment]
> The model is loaded correctly and displayed, the image is generated but it is empty.

@gggggbbbbb i tested on my project like as you do. Generated **data url** is not empty but **image** is empty.


`const image =  renderer.domElement.toDataURL(); // The default format type is image/png` 

this generates:
https://gist.githubusercontent.com/rokumatsumoto/8061386968e885cd69c70c315ca6cf7b/raw/91a91d003354de0a615650524916c433adc09cf8/gistfile1.txt

@gggggbbbbb You can see a working example here.
https://stackoverflow.com/a/26197858/2015025

```javascript
renderer = new THREE.WebGLRenderer({
                    preserveDrawingBuffer: true
                });
```

> preserveDrawingBuffer flag will help you to get the base64 encoding of the current frame

![Screen Shot 2019-07-28 at 12 17 34](https://user-images.githubusercontent.com/28678254/62004796-54c21f00-b132-11e9-8c74-51e83fb08181.png)

@joaquinco how can we set **preserveDrawingBuffer** to true, or should we do?

**Comment by gggggbbbbb** [comment]
Hello, any update on this? @hujiulong could you advise us on how to set **preserveDrawingBuffer** to true and whether this could solve our issue? Thank you!

**Comment by hujiulong** [comment]
In version 1.1.1, you can use `glOptions` to set up `preserveDrawingBuffer`.
```vue
<model-obj :glOptions="{ preserveDrawingBuffer: true }" />
```

**Comment by gggggbbbbb** [comment]
Thanks @hujiulong! Unfortunately, I am still not able to generate a screenshot even though `preserveDrawingBuffer` is `true` (I also double-checked I'm using version 1.1.1). Current behaviour is that the generated png file is empty. I'm reporting here below the current version of the code, could you please advise if there is anything wrong with it? Thanks

```
<template>
    <div  >
      <model-stl :glOptions="{ preserveDrawingBuffer: true }" ref="model" src="/static/models/gear.stl"></model-stl>
      <button @click="takeSnap">Snapshot</button>
    </div>    
</template>

<script>
import ModelStl  from 'vue-3d-model/src/model-stl.vue'
export default {
  components: {ModelStl} ,
  methods:{
     takeSnap(){
      let {renderer}  = this.$refs.model;
      let image =  renderer.domElement.toDataURL("image/png", 1);
      window.open(image); 
    },
  }
}
</script>
```

**Comment by hujiulong** [comment]
@gggggbbbbb I added a [screenshot example](https://hujiulong.github.io/vue-3d-model/#/demo-snapshot). 

![image](https://user-images.githubusercontent.com/13267437/65223460-d3648880-daf3-11e9-95fd-d1ef4180c88d.png)
