### ISSUE TITLE
用.obj的文件渲染没有没有颜色，全是黑的。

### ISSUE THREAD

**Issue by zengjielin** [hujiulong/vue-3d-model#113]
[演示地址](https://packer-static-assets.oss-cn-shenzhen.aliyuncs.com/5ca860152dafb9605ad99634afe829981562988381754.mp4)

**Comment by hujiulong** [comment]
obj文件本身只有几何信息，没有材质信息。如果想要有材质信息的话，需要配合mtl文件。
[obj-mtl](https://hujiulong.github.io/vue-3d-model/#/demo-obj-mtl)

**Comment by zengjielin** [comment]
好的，谢谢。
