### ISSUE TITLE
能不能在模型的不同位置显示不同标签，位置现在可以打印出来，但这个标签怎么弄呢？在哪写（不需要一直正对屏幕）

### ISSUE THREAD

**Issue by wuafan** [hujiulong/vue-3d-model#117]

**Comment by hujiulong** [comment]
这种特定场景的需求还是用three.js做吧，vue-3d-model只是一个简单地展示模型的组件。

**Comment by wuafan** [comment]
谢谢老师




------------------ 原始邮件 ------------------
发件人: "hujiulong"<notifications@github.com>;
发送时间: 2019年7月23日(星期二) 下午5:25
收件人: "hujiulong/vue-3d-model"<vue-3d-model@noreply.github.com>;
抄送: "吴凡"<929523653@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [hujiulong/vue-3d-model] 能不能在模型的不同位置显示不同标签，位置现在可以打印出来，但这个标签怎么弄呢？在哪写（不需要一直正对屏幕） (#117)




这种特定场景的需求还是用three.js做吧，vue-3d-model只是一个简单地展示模型的组件。
