### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by Gcagny** [hujiulong/vue-3d-model#12]
Hi,
I'm tryingt o use your component in my project but when i start my project i have a : "Uncaught Error: Unexpected line: '{'" in "vue-3d-model.js.min.
Do you know why i have this err ?

**Comment by hujiulong** [comment]
hi, can you add more information about the error? I can't reproduce the problem, I suggest you write a demo on jsfiddle to show the problem.

**Comment by Gcagny** [comment]
HI,
It was my mistake, the error occured because i used a json format.
It works fine with a .obj.
I close the subject.
