### ISSUE TITLE
全屏问题

### ISSUE THREAD

**Issue by fastenCh** [hujiulong/vue-3d-model#121]
我想在Android中通过Webview加载模型，但是模型区域没有全屏，怎么处理

**Comment by hujiulong** [comment]
提供复现代码和渲染结果截图

**Comment by lovechenghao** [comment]
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>vue-3d-model</title>
	<body>
	  <div id="app">
		<model-stl src="gear.stl"></model-stl>
	  </div>
	<script src="vue.js"></script>
	<script src="vue-3d-model.js"></script>
	<script>
	  new Vue({ el: '#app' });
	</script>
</html>


![](https://user-images.githubusercontent.com/29998950/64434519-497bef00-d0f3-11e9-843e-b7a1650987f9.jpg)

**Comment by lovechenghao** [comment]
![](https://user-images.githubusercontent.com/29998950/64434688-b3949400-d0f3-11e9-8b24-4f3ffe559627.jpg)
