### ISSUE TITLE
Delete model objects

### ISSUE THREAD

**Issue by JWDobken** [hujiulong/vue-3d-model#125]
Is it possible to delete all or specific model objects?
The opposite of `model.addObject`?

**Comment by hujiulong** [comment]
You can implement it yourself based on `addObject`
https://github.com/hujiulong/vue-3d-model/blob/1ca967c0bdf450aa6656278f29894262587960c5/src/model-mixin.vue#L458-L469

The simplest way：
```js
this.$refs.model.wrapper.remove(this.$refs.model.object);
```
`AddObject` and the other variables and methods used above are used internally only. Don't rely too much on them.
