### ISSUE TITLE
纯gltf是不是不支持，必须是带bin的gltf才支持

### ISSUE THREAD

**Issue by Carolineliu** [hujiulong/vue-3d-model#136]

**Comment by hujiulong** [comment]
都支持

**Comment by Carolineliu** [comment]
> 都支持
使用<model-collada src="model.gltf"></model-collada>报错
THREE.ColladaLoader: Failed to parse collada file.
 error on line 1 at column 1: Document is empty
Cannot read property 'scene' of null

**Comment by hujiulong** [comment]
gltf格式应该用`model-gltf`
