### ISSUE TITLE
你好，请问如果我想在一个场景里添加两个模型，该模块可以实现吗？

### ISSUE THREAD

**Issue by HZP1995** [hujiulong/vue-3d-model#14]
具体情况是，我想在一个场景里添加两个模型，一个3D模型是底图，另一个3D模型会利用position属性在底图上移动，类似于3D底图，请问该模块可以实现吗？谢谢！

**Comment by hujiulong** [comment]
不能哦，这个项目只是想简化模型展示的过程，如果有比较复杂的逻辑的话建议直接用`three.js`
