### ISSUE TITLE
On error event

### ISSUE THREAD

**Issue by Pujomir** [hujiulong/vue-3d-model#15]
Hi,

I found a problem in your code.
The "on-error" event actually gives a progress event.
That is because at line 446 of the file "model-mixin.vue" you are passing the error handler as the 3rd
parameter of the load method when in fact the error handler should be the 4th parameter.
Also it would be nice if you could add an "on-progress" event as well.

Thank you for looking into this

**Comment by hujiulong** [comment]
thanks! Do you want to make a PR for this?
