### ISSUE TITLE
Problem with gestion of light.

### ISSUE THREAD

**Issue by Pierre-Genest** [hujiulong/vue-3d-model#164]
Hello,

I am trying to use this module and I don't find where to change the lights options or what to put in the var lights array to change it.
Do you have any solution?

**Comment by hujiulong** [comment]
The format of lights:
https://github.com/hujiulong/vue-3d-model/blob/17c7bde00adc85e9bdf42f4931976af979ad9eea/src/model-ply.vue#L16-L30

**Comment by bmwQAQ** [comment]
在我的项目中要怎样改灯光呢
