### ISSUE TITLE
How do I set the source in Javascript?

### ISSUE THREAD

**Issue by magicmikek** [hujiulong/vue-3d-model#18]
I am downloading the data after the user uploaded the files on the website.
How do I set the source of the 3D model object and set the right model container?

`var model = document.getElementById("app").src "source"
        new Vue({
            el: '#app',
            data: {
                rotation: {
                    x: -Math.PI / 2,
                    y: 0,
                    z: 0
                }
            },
            methods: {
                onLoad () {
                    this.rotate();
                },
                rotate () {
                    this.rotation.z += 0.01;
                    requestAnimationFrame( this.rotate );
                }
            }
        })`

**Comment by hujiulong** [comment]
hmm.. I'm not sure what you mean, I can't see what you want to do from your code.
