### ISSUE TITLE
FBX加载失败

### ISSUE THREAD

**Issue by 544447** [hujiulong/vue-3d-model#193]
失败报错： 
Uncaught Error: THREE.OBJLoader: Unexpected line: "Kaydara FBX Binary �FBXHeaderExtension\FBXHeaderVersionI�x"
 at OBJLoader.parse (vue-3d-model.umd.js?fc50:51381)
    at Object.eval [as onLoad] (vue-3d-model.umd.js?fc50:51142)
    at XMLHttpRequest.eval (vue-3d-model.umd.js?fc50:36650)

**Comment by 544447** [comment]
Uncaught Error: THREE.OBJLoader: Unexpected line: "; FBX 7.5.0 project file"

**Comment by hujiulong** [comment]
现在不支持加载FBX模型，支持的类型看[这个列表](https://github.com/hujiulong/vue-3d-model#model-format-support)

**Comment by wangerzi** [comment]
支持 fbx 模型的那个 commit 我提过，我这边用同样的方法加载 fbx 模型倒还行，是用的 <model-fbx> 么，为何会出现 OBJLoader，有印象这里是用的 fbxloader.

https://github.com/hujiulong/vue-3d-model/blob/65bf0e21e5882de99b0ea1a64b0d6648cdfe73a7/src/model-fbx.vue#L32

**Comment by hujiulong** [comment]
@wangerzi 你加了fbx支持，但我还没有发npm包😅，所以现在还是不支持的。估计这位同学是用了model-obj

**Comment by hujiulong** [comment]
更新到[vue-3d-model@1.3.1](https://www.npmjs.com/package/vue-3d-model/v/1.3.1)，然后用model-fbx来加载模型

**Comment by 544447** [comment]
老哥，http://www.hujiulong.com/访问不了啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hujiulong/vue-3d-model"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年6月30日(星期二) 中午11:49
收件人:&nbsp;"hujiulong/vue-3d-model"<vue-3d-model@noreply.github.com&gt;;
抄送:&nbsp;"544447"<85393485@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hujiulong/vue-3d-model] FBX加载失败 (#193)





 
更新到vue-3d-model@1.3.1，然后用model-fbx来加载模型
