### ISSUE TITLE
Browser out of memory when loading fbx model.

### ISSUE THREAD

**Issue by rootlittledev** [hujiulong/vue-3d-model#197]
Basically, when I load the .fbx model the browser after a few seconds shows an out of memory page.
Here is the console output:
https://gyazo.com/f803de01815ea677916da8e5ef22bb7e

vue-3d-model: 1.3.1,
vue: 2.6.10,
model: simple 3d character model(with textures).

Code:
```<v-col align="center" justify="center" v-if="edit">
            <v-flex xs8>
                    <v-card
                            class="mx-auto, mb-4"
                            outlined>
                        <v-list-item three-line>
                            <v-list-item-avatar
                                    tile
                                    size="700"
                            ><model-obj :backgroundAlpha="alpha" src="/models/jahy_sama_textures.fbx" ></model-obj></v-list-item-avatar>
                            <v-list-item-content>
                                <v-chip v-for="(index, option) in this.currentModel.options"
                                :key="index">
                                    {{option}}
                                </v-chip>
                                <v-list-item-title class="headline mb-1">{{this.currentModel.name}}</v-list-item-title>
                                <v-list-item-subtitle>{{this.currentModel.description}}</v-list-item-subtitle>
                            </v-list-item-content>
                        </v-list-item>
                    </v-card>
            </v-flex>
```

**Comment by hujiulong** [comment]
You should use the `model-fbx` to load the FBX model, not `model-obj`.

**Comment by rootlittledev** [comment]
Sorry my mistake, I mindlessly copied the code from the live demo.

**Comment by rootlittledev** [comment]
Also not really related to this issue but maybe you could help. https://gyazo.com/06b950cdde6a2f4581946bcee6f1f541
As you can see the model imported has some weird noise. Any clue?

**Comment by wangerzi** [comment]
> Also not really related to this issue but maybe you could help. https://gyazo.com/06b950cdde6a2f4581946bcee6f1f541
> As you can see the model imported has some weird noise. Any clue?

Hi, I'm also confused by this question a few month ago, and got the answer at segmentfault, you should modify your webgl renderer options as this

```js
var renderer = new THREE.WebGLRenderer({ logarithmicDepthBuffer: true });
```

refer: https://segmentfault.com/q/1010000014379650/a-1020000021860264 and https://www.cnblogs.com/lst619247/p/9098845.html
