### ISSUE TITLE
用鼠标转动的时候，背面没有光照

### ISSUE THREAD

**Issue by miao2017** [hujiulong/vue-3d-model#2]
加载的obj模型，主要有两个问题，一个是背面没有光照，另外一个是皮肤不光滑。我看vue-3d-model里默认是用的是this.shading = SmoothShading; // THREE.FlatShading, THREE.SmoothShading
？？？

代码如下：
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
    </head>
    <body>
        <div id="app">
            <model-obj src="girl_base.obj"></model-obj>
        </div>
        <script src="https://cdn.bootcss.com/vue/2.2.2/vue.min.js"></script>
        <script src="vue-3d-model.js"></script>
        <script>
        new Vue({
            el: '#app'
        })
        </script>
    </body>
</html>
```

**Comment by hujiulong** [comment]
model-obj会自动添加一个默认光照，但是你也可以根据自己需要来调节
可以给组件传一个lights,它是一个数组
```html
<model-obj src="xx.obj"
    :lights="[
        {
            type: 'DirectionalLight',           // 灯光类型
            position: { x: 1, y: 1, z: 1 },     // 灯光位置
            color: 0xffffff,
            intensity: 0.8
        }
    ]">        
</model-obj>
```
灯光类型可以是`AmbientLight`,`PointLight `,`DirectionalLight `,`HemisphereLight `
灯光具体的参数可以看看[threejs的文档](https://threejs.org/docs/index.html)，组件中处理灯光的代码在[这里](https://github.com/hujiulong/vue-3d-model/blob/master/src/model-mixin.vue#LC340)

另外模型表面不光滑是因为没有计算**顶点法线**，你可以试试这样
```html
// ...
<model-obj src="xx.obj" ref="obj" @on-load="onLoad">    
</model-obj>
// ...
<script>
new Vue( {
    el: '#app',
    methods: {
        onLoad: function() {
            var object = this.$refs.obj.object;
            object.geometry.computeVertexNormals();
            this.$refs.obj.render();
        }
    }
} )
</script>
```

**Comment by miao2017** [comment]
恩，我试了一下，第一个问题倒是不大，我可以在背面再添加一个光源。

第二个问题，按照你的方法会报错

Uncaught TypeError: Cannot read property 'computeVertexNormals' of undefined

**Comment by hujiulong** [comment]
对了，这里的object应该是一个组，那你修改一下
```javascript
new Vue( {
    el: '#app',
    methods: {
        onLoad: function() {
            var object = this.$refs.obj.object;
            object.traverse( function( child ) {
                if ( child.geometry ) {
                    child.geometry.computeVertexNormals();
                }
            } )
            this.$refs.obj.render();
        }
    }
} )
```

**Comment by miao2017** [comment]
好想没效果。。。是我哪里写错了吗？


<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">

</head>
<body>
    <div id="app">
        <model-obj src="http://appbucket.orbbec.me/orbbec/img/2017/06/20/girl_base.obj" ref="obj" @on-load="onLoad"></model-obj>
    </div>
    <script src="https://cdn.bootcss.com/vue/2.2.2/vue.min.js"></script>
    <script src="vue-3d-model.js"></script>
    <script>
        new Vue({
            el: '#app',
            methods: {
                onLoad: function() {
                    var object = this.$refs.obj.object;
                    object.traverse( function( child ) {
                        if ( child.geometry ) {
                            child.geometry.computeVertexNormals();
                        }
                    })
                    this.$refs.obj.render();
                }
            }
        })
</script>
</body>






miaokuanghua@orbbec.com
 
发件人： Jiulong Hu
发送时间： 2017-06-22 14:17
收件人： hujiulong/vue-3d-model
抄送： miao2017; Author
主题： Re: [hujiulong/vue-3d-model] 用鼠标转动的时候，背面没有光照 (#2)
对了，这里的object应该是一个组，那你修改一下
new Vue( {
    el: '#app',
    methods: {
        onLoad: function() {
            var object = this.$refs.obj.object;
            object.traverse( function( child ) {
                if ( child.geometry ) {
                    child.geometry.computeVertexNormals();
                }
            } )
            this.$refs.obj.render();
        }
    }
} )

**Comment by miao2017** [comment]
试了下，不是光滑的

**Comment by hujiulong** [comment]
可能还有别的原因，我下个版本在`model-obj`加一个光滑的选项吧。明天你再看看

**Comment by miao2017** [comment]
ok，感谢。你这是为人民服务呀！！！！



miaokuanghua@orbbec.com
 
发件人： Jiulong Hu
发送时间： 2017-06-22 14:26
收件人： hujiulong/vue-3d-model
抄送： miao2017; Author
主题： Re: [hujiulong/vue-3d-model] 用鼠标转动的时候，背面没有光照 (#2)
可能还有别的原因，我下个版本在model-obj加一个光滑的选项吧。明天你再看看

**Comment by hujiulong** [comment]
现在`model-obj`可以添加一个`smoothing`选项。不过这个方法可能有些不易发现的问题，还是建议在建模软件中去生成法线

使用方法：
```vue
<model-obj src="xxx.obj" smoothing></model-obj>
```

**Comment by miao2017** [comment]
加了smoothing没变化。代码参看如下。你可以再浏览器运行试试。可以运行的

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">

</head>
<body>
    <div id="app">
        <model-obj src="http://appbucket.orbbec.me/orbbec/img/2017/06/20/girl_base.obj" ref="obj" @on-load="onLoad" smoothing></model-obj>
    </div>
    <script src="https://cdn.bootcss.com/vue/2.2.2/vue.min.js"></script>
    <script src="http://appbucket.orbbec.me/orbbec/scannerjs/vue-3d-model.js"></script>
    <script>
        new Vue({
            el: '#app',
            methods: {
                onLoad: function() {
                    var object = this.$refs.obj.object;
                    object.traverse( function( child ) {
                        if ( child.geometry ) {
                            child.geometry.computeVertexNormals();
                        }
                    })
                    this.$refs.obj.render();
                }
            }
        })
</script>
</body>




miaokuanghua@orbbec.com
 
发件人： Jiulong Hu
发送时间： 2017-06-22 21:43
收件人： hujiulong/vue-3d-model
抄送： miao2017; Author
主题： Re: [hujiulong/vue-3d-model] 用鼠标转动的时候，背面没有光照 (#2)
现在model-obj可以添加一个smoothing选项。不过这个方法可能有些不易发现的问题，还是建议在建模软件中去生成法线
使用方法：
<model-obj src="xxx.obj" smoothing></model-obj>

**Comment by hujiulong** [comment]
忘记更新编译后的文件了，现在更新了

**Comment by miao2017** [comment]
可以了，谢谢

**Comment by caoxiaofei3** [comment]
> 恩，我试了一下，第一个问题倒是不大，我可以在背面再添加一个光源。
> 
> 现在这个灯光是跟着模型一起转动的吗？
> 
> 第二个问题，按照你的方法会报错
> 
> 未捕获的TypeError：无法读取未定义的属性“computeVertexNormals”
请问：怎么样在背面再添加一个光源？
