### ISSUE TITLE
ply格式不能显示

### ISSUE THREAD

**Issue by jingxa** [hujiulong/vue-3d-model#22]
大哥，你好，我在测试ply文件的时候，使用的html方法，但是在显示中，不能形成cavas标签，还是model-lply，如果我使用一个web服务器打开，提示我model-ply标签没有rotation这个属性；就是不能显示？请问我该如何解决这个问题呢？

**Comment by hujiulong** [comment]
谢谢反馈，是我忘记导出`model-ply`了，现在已经修复了，你可以重新安装一下。

**Comment by jingxa** [comment]
哈哈。谢谢大哥了！

**Comment by jingxa** [comment]
大哥。在麻烦一下。我主要使用script来使用，但是你的js好像还是不能用。。
```
vue:6 ReferenceError: rotation is not defined
    at Rt.eval (eval at Tn (vue:6), <anonymous>:2:107)
    at Rt.t._render (vue:6)
    at Rt.r (vue:6)
    at Kr.get (vue:6)
    at new Kr (vue:6)
    at vue:6
    at Rt.$mount (vue:6)
    at Rt.$mount (vue:6)
    at Rt.t._init (vue:6)
    at new Rt (vue:6)
```
我先试试npm。。麻烦你了。。谢谢！

**Comment by jingxa** [comment]
还有ply对于格式有要求吗，ascii，或者2进制？还有纯点云数据可以显示么？还是 只能显示网格？谢谢

**Comment by hujiulong** [comment]
这个报错是你代码的问题
```javascript
<model-ply src="bun_zipper.ply" :rotation="rotation"></model-ply>
```
这里表示你将一个变量`rotation`传入，但是从你下面的代码来看，实际上没有这个变量。你需要把`:rotation="rotation"`去掉

-----
我看了下，是因为我示例代码里多写了这个，我晚点改掉

**Comment by jingxa** [comment]
haha ,谢谢了。我以为这个属性是ply的标签属性，谢谢你的解答啦。谢谢！
