### ISSUE TITLE
Fallback?

### ISSUE THREAD

**Issue by codanator** [hujiulong/vue-3d-model#24]
Hey,

i need do add a fallback image if the cliebt browser does not support any of the threejs renderes.
How wuold you to this?

thx for your help!

**Comment by hujiulong** [comment]
```html
<model-obj>
    <!-- fallback content -->
</model-obj>
```
so you can display a image when the browser does not support webgl, like this:
```html
<model-obj>
    <img src="image.png" />
</model-obj>
```
