### ISSUE TITLE
引入之后报错如下：vue-3d-model.umd.js?e360:13754 THREE.BufferGeometry.computeBoundingSphere(): Computed radius is NaN. The "position" attribute is likely to have NaN values.

### ISSUE THREAD

**Issue by helen1314181** [hujiulong/vue-3d-model#247]
THREE.BufferGeometry.computeBoundingSphere(): Computed radius is NaN. The "position" attribute is likely to have NaN values

应该怎么解决呢？

**Comment by hujiulong** [comment]
这应该是你的模型数据有问题，你弄一个能复现问题的demo吧

**Comment by helen1314181** [comment]
> 这应该是你的模型数据有问题，你弄一个能复现问题的demo吧

您好，这个模型数据需要怎么弄出来呢？我现在应该没有数据

**Comment by helen1314181** [comment]
解决了，是因为引用的资源路径不对，更改路径就可以了
