### ISSUE TITLE
Camera settings

### ISSUE THREAD

**Issue by AaronBison** [hujiulong/vue-3d-model#256]
Hey! :D
I've been using this plugin for my state exam project and I'm very pleased so far.
Although I have a few questions for example is there any way to change the camera behavior? I mean can I change the one-point perspective of the camera to a first-person camera type?

**Comment by hujiulong** [comment]
Changing the camera type is not supported now.

**Comment by AaronBison** [comment]
Alright, my problem is that I want to be able to move inside the 3Dmodel. For that, I am using coordinates right now, but the problem is that every time the camera turns from the initial setting, the coordinates will be inaccurate because the camera is a one-point cam. 
Do you guys have any solution or advice on how can I accomplish the movement inside the 3D model? :)
