### ISSUE TITLE
Camera movement improvements

### ISSUE THREAD

**Issue by AaronBison** [hujiulong/vue-3d-model#258]
Alright, my problem is that I want to be able to move inside the 3Dmodel. For that, I am using coordinates right now, but the problem is that every time the camera turns from the initial setting, the coordinates will be inaccurate because the camera is a one-point cam.
Do you guys have any solution or advice on how can I accomplish the movement inside the 3D model? :)

**Comment by hujiulong** [comment]
Can you make a demo so that I can understand your question more clearly.

**Comment by AaronBison** [comment]
[Here is the code](https://gist.github.com/AaronBison/73644e5aac9a83da7e48bc7be1cd7111)
![a Vue problem 1](https://user-images.githubusercontent.com/37123069/101734474-fe584500-3ac8-11eb-8f5d-4bac0c57ccb2.gif)
![a Vue problem 2](https://user-images.githubusercontent.com/37123069/101734480-01ebcc00-3ac9-11eb-9132-be1b7f75e7d1.gif)

**Comment by wangerzi** [comment]
You can  try to set cameraLookAt prop, at `model-gltf` just like

```js
<template>
<model-gltf ref="obj" :camera-look-at="lookPos">
</template>
<script>
...
computed: {
  lookPos() {
     // dynamic got pos from object what you want to look at (child object from this.$refs['obj'])
  }
}
...
</script>
```

**Comment by wangerzi** [comment]
Refer to source code:

https://github.com/hujiulong/vue-3d-model/blob/27b5d1c6f2d0b3da0170ea7e84e40d36e7c76a9b/src/model-mixin.vue#L334-L361

**Comment by AaronBison** [comment]
I'll give it a try, thank you! :)
