### ISSUE TITLE
光源设置问题

### ISSUE THREAD

**Issue by zhaoyixun** [hujiulong/vue-3d-model#26]
请问lights 怎么设置，看到参数里有个lights，估计是光源吧，但是没说明怎么设置呢？

**Comment by hujiulong** [comment]
lights是一个数组，它的值是这样子
https://github.com/hujiulong/vue-3d-model/blob/17c7bde00adc85e9bdf42f4931976af979ad9eea/src/model-ply.vue#L16-L31

**Comment by zhaoyixun** [comment]
非常感谢，我试试

**Comment by xiaoxiaotian** [comment]
怎么样显示打光的影子啊
