### ISSUE TITLE
这个库的意义在哪？都是一些皮毛功能，要是能把cesiumJS封成VUE组件那可是太好了

### ISSUE THREAD

**Issue by liucaidong** [hujiulong/vue-3d-model#260]
功能太简单了，可以参照这个库https://github.com/cesiumlab/XbsjEarthUI，也是VUE封装，可惜不支持react

**Comment by hujiulong** [comment]
这是我大学时做的一个项目，功能确实不多，因为只是想解决展示3D模型这一个小需求。简单的库复杂的库都有各自的场景，不至于没有意义。

**Comment by liucaidong** [comment]
好吧，其实我是从项目的角度来考虑的，因为很少有项目是只需要展示模型就可以的，都是需要交互，点选，分析等等复杂的操作，最简单的点选变色功能肯定是需要的，
