### ISSUE TITLE
Enabling vertexColors for .ply models

### ISSUE THREAD

**Issue by geni94** [hujiulong/vue-3d-model#274]
I'm having an issue loading an `.ply` file using your (real nice) library.
I can currently render the object, modify the lighting accordingly, etc. However, I'm trying to activate the vertex colors for the object so that it would also render colors. From the documentation, I believe it would possible using the `glOptions` prop.

From the documentation of WebGL and three, I found that this is most likely under the `.capabilities` object https://threejs.org/docs/index.html#api/en/renderers/WebGLRenderer.capabilities , however it is a bit unclear how to use this in your library.

I've tried a couple of options, such as assigning the following
```
capabilities: {
    floatVertexTextures: true,
},
```
to `:glOptions` but to no effect.

Any guidance or idea?

**Comment by wangerzi** [comment]
https://github.com/hujiulong/vue-3d-model/blob/40b077a3513f0830d1ba28a3c653b401b7ac97b2/src/model-mixin.vue#L157-L169

I tried to update in demo-ply.vue, it's usable.

![image](https://user-images.githubusercontent.com/22190579/109588386-99e6d800-7b43-11eb-9d47-99b13eb39b61.png)


```vue
<template>
  <demo-block :vue-code="code" :html-code="htmlCode">
    <template slot="preview">
      <model-ply
        ref="model"
        :backgroundAlpha="0"
        @on-load="onLoad"
        :rotation="rotation"
        :gl-options="glOptions"
        src="static/models/ply/binary/Lucy100k.ply"
      ></model-ply>
      <div class="example-loading" v-show="loading"></div>
    </template>
  </demo-block>
</template>

<script>
import DemoBlock from '../components/demo-block.vue';
import ModelPly from '../../src/model-ply.vue';

const code = `
<template>
    <model-ply src="static/models/ply/slotted_disk.ply"></model-ply>
</template>

<script>
    import { ModelPly } from 'vue-3d-model'

    export default {
        components: {
            ModelPly
        }
    }
<\/script>
`;

const htmlCode = `
<body>
    <div id="app">
        <model-ply src="static/models/ply/slotted_disk.ply"></model-ply>
    </div>
    #scripts#
    <script>
        new Vue({
            el: '#app'
        })
    <\/script>
</body>
`;

export default {
  name: 'demo-ply',
  data() {
    return {
      code,
      htmlCode,
      loading: true,
      glOptions: {
        capabilities: {
          floatVertexTextures: true,
        },
      },
      rotation: {
        x: 0,
        y: Math.PI,
        z: 0,
      },
    };
  },
  methods: {
    onLoad() {
      this.loading = false;
      console.log(this.$refs.model.renderer);
    },
  },
  components: {
    ModelPly,
    DemoBlock,
  },
};
</script>
```

**Comment by geni94** [comment]
Thanks for the help @wangerzi this approach worked out just fine in my case too :100:

**Comment by Yan-wei-yu** [comment]
sorry I use ref  and :gl-options="glOptions"

My Script
```
const glOptions = ref();
glOptions.value=
{ glOptions: {
        capabilities: {
          floatVertexTextures: true,
        },
      },
      }
```
I can;t work my ply model
