### ISSUE TITLE
Textures

### ISSUE THREAD

**Issue by boraacici** [hujiulong/vue-3d-model#276]
Hello to everyone,

Very happy when I saw this library because it was exactly what I needed. I have a few models and I want to show them to users.

But I could not see any information about texture in the readme page. Is it possible to add textures to models ?

Best Regards

**Comment by hujiulong** [comment]
Many model formats contain textures information, such as gltf/dae, so it is not necessary to add texture manually.

**Comment by boraacici** [comment]
So we can't add texture manually, right ?

Thanks !
