### ISSUE TITLE
Combine two renders.

### ISSUE THREAD

**Issue by RobJmz** [hujiulong/vue-3d-model#29]
Is there a way to render two components into same canvas?

Right now I can change the color by using $refs:

```
var object = this.$refs.model.object;
object.children[0].material.color.setStyle('#000')
```

But i wish to add for example a skateboard:
Deck
Wheels

And change the colors with something like this:
```
var object = this.$refs.model.object;
object.children[0].material.color.setStyle('#000')
object.children[1].material.color.setStyle('#ff0000')
```

Is there any way to include this to the canvas?

Thanks in advance.

**Comment by hujiulong** [comment]
there's no simple way, you can try using three.js directly.
