### ISSUE TITLE
切换模型，已加载完成的模型会停留

### ISSUE THREAD

**Issue by jackliu18** [hujiulong/vue-3d-model#298]
我在问题里也搜过很多类似有过同样问题，就是切换模型原有的不会去掉。看到有回答“切换时销毁原来的”，请问一下如何处理，感谢！

**Comment by hujiulong** [comment]
有很多方法，可以试试[这个](https://forum.vuejs.org/t/how-to-destroy-and-rerender-component/43807)

**Comment by jackliu18** [comment]
成了！非常感谢！
