### ISSUE TITLE
如何使导入的obj模型在屏幕中显示固定的比例

### ISSUE THREAD

**Issue by superSheng11** [hujiulong/vue-3d-model#3]
现在有个需求，就是导入的obj模型大小是不固定，如何去实现动态的计算来实现模型在屏幕中显示合适的比例，比如模型占屏幕中的60%，大神求解答，谢谢

**Comment by hujiulong** [comment]
`vue-3d-model`会自己调整相机位置，让模型以合适的大小渲染出来，你可以认为默认是占100%，但是这个比例不能自己调节。你可以在外面再套一个容器，让里面显示模型的组件宽度占容器的60%
