### ISSUE TITLE
关于拖拽旋转的问题

### ISSUE THREAD

**Issue by zhaoyixun** [hujiulong/vue-3d-model#30]
你好，关于光源的设置问题解决了，非常谢谢！

另外我发现模型渲染完毕后，鼠标拖拽模型水平旋转（绕着y轴）是没有任何问题，但是拖拽模型垂直旋转（绕着x轴），最多只能朝上旋转90度，朝下旋转90度，请问怎样才能像水平旋转那样无限制旋转呢？

**Comment by hujiulong** [comment]
这个牵涉到计算上的问题，而且对于大多数情况，使用者不会希望旋转到90度以后继续旋转看到颠倒的场景

**Comment by zhaoyixun** [comment]
嗯，明白，但是有时我加载一个模型后原始位置是倒放的，然后我就始终不能的转到一个位置舒服的浏览，很郁闷，最好有一个地方能修改这个问题就好了！

**Comment by hujiulong** [comment]
你可以设置rotation属性来旋转模型

**Comment by zhaoyixun** [comment]
...，呵呵，兄弟啊，这个治标都没治好，期待你的下一个版本能能在实例化时做个拖拽旋转配置就很完美了。
