### ISSUE TITLE
关于加载gltf只生成canvas未加载模型

### ISSUE THREAD

**Issue by jackliu18** [hujiulong/vue-3d-model#300]
起初以为是导出模型的问题，后来我引用demo 中的gltf 也出现了同样的问题
`<model-gltf 
        src="models/Duck/glTF/Duck.gltf" 
        
        :lights="lights"
        backgroundColor="#000000"
        :backgroundAlpha="alpha"
      ></model-gltf>`

`import { ModelObj, ModelStl, ModelCollada, ModelFbx, ModelGltf } from "vue-3d-model";
import { listAssets } from "@/api/business/building/buildingView";
export default {
  components: { ModelObj, ModelStl, ModelCollada, ModelFbx, ModelGltf },`

但最重还是只显示canvas 里面却没有模型 请问该如何修复这个问题

**Comment by jackliu18** [comment]
@hujiulong 其实我想说的是 代码没有报错的问题，只是单纯的模型不显示了

**Comment by hqzh** [comment]
duck那个是有一个图片的，你放在了同一个目录了吗

**Comment by jackliu18** [comment]
> duck那个是有一个图片的，你放在了同一个目录了吗

嗯 在同一个目录了，刚刚模型出来了
