### ISSUE TITLE
支不支持项目里对gltf模型压缩的处理？

### ISSUE THREAD

**Issue by jackliu18** [hujiulong/vue-3d-model#303]
因为目前单个模型过大，而且还是单页面通过v-if切换展示不同模型，所以转换了体积最小的格式gltf，开发环境下，加载速度还算较快，但是部署到nginx访问就很慢了，后来从网上搜到一个draco的这个东西，是基于three.js loader时候进行压缩的软件 不知道v3m可不可以兼容这个插件

**Comment by wangerzi** [comment]
印象中还未集成，只能自己改改把 draco 加载进去，因为 threejs 加载 draco 的特殊，之前是将 draco 资源包放到 public 下，再指定路径加载的。

**Comment by jackliu18** [comment]
> 印象中还未集成，只能自己改改把 draco 加载进去，因为 threejs 加载 draco 的特殊，之前是将 draco 资源包放到 public 下，再指定路径加载的。

我在node modules 源码里添加了draco压缩代码，但是静态文件应该怎么放，路径怎么引？
