### ISSUE TITLE
glTF格式模型加载不完整

### ISSUE THREAD

**Issue by soDoEasy** [hujiulong/vue-3d-model#304]
原模型截图
![image](https://user-images.githubusercontent.com/57608792/131767069-f4463cd4-54c5-4a77-809e-417beb710893.png)
这个是加载后的模型截图 
![image](https://user-images.githubusercontent.com/57608792/131767097-7a8d3ea6-df28-4485-a703-b5f3f5e2ffa6.png)
在线测试地址 http://101.201.35.85/web3d-demo/index.html

**Comment by ByNamePfWang** [comment]
有人遇到过这个问题吗？

**Comment by wangerzi** [comment]
> 有人遇到过这个问题吗？

看起来有点像没加光照，也有点像原模型导出的时候，材质贴图没渲染上，或者 gltf 格式的模型页面上没加载成功，并且预览链接打不开。

**Comment by soDoEasy** [comment]
> 看起来有点像没加光照，也有点像原模型导出的时候，材质贴图没渲染上，或者 gltf 格式的模型页面上没加载成功，并且预览链接打不开。

https://github.com/soDoEasy/web3d-demo  你可以看一下这个地址 我把代码以及3D模型都上传了

**Comment by soDoEasy** [comment]
问题已经解决了, 确实是没有加光照 
添加如下代码解决问题
lights:[
				{ 
					 type: 'HemisphereLight', 
					 position: { x: 300, y: 300, z: 300 }, 
					 skyColor: 0xffffff, 
					 groundColor: 0xffffff, 
					 intensity: 0.6
				 }
				 , 
				 { 
					 type: 'DirectionalLight', 
					 position: { x: 600, y: 600, z: 600 }, 
					 color: 0xffffff, 
					 intensity: 7
				 } 
			]
