### ISSUE TITLE
如何设置让模型的Y轴不能为付的或者是大于某个值

### ISSUE THREAD

**Issue by soDoEasy** [hujiulong/vue-3d-model#306]
目的是不让模型旋转到模型地面一下

**Comment by wangerzi** [comment]
虽然不是特别理解意思，但可以通过 box3d 拿到模型的大小，然后展示设置模型位置的 y 为 box3d 拿到的盒子高度 /2，模型水平转怎么都不会让模型处于 y 轴下方的。

**Comment by soDoEasy** [comment]
我去试试
