### ISSUE TITLE
是否支持切换相机位置以及模型旋转到某一位置然后固定

### ISSUE THREAD

**Issue by locta66** [hujiulong/vue-3d-model#32]
请问是否支持

**Comment by hujiulong** [comment]
你说的固定是什么意思，不能再操作吗？你可以通过`controllable `来设置是否能操作

**Comment by locta66** [comment]
好的，谢谢你的回复，另外，怎么旋转模型到一个特定的位置呢，另外我尝试设置模型传入position参数也没有任何变化，请问有例子吗 我在example中没有找到？

**Comment by hujiulong** [comment]
传rotation
https://hujiulong.github.io/vue-3d-model/#/demo-rotate
