### ISSUE TITLE
CORS Problem

### ISSUE THREAD

**Issue by odai-alali** [hujiulong/vue-3d-model#33]
Hi, Thank you for this nice components.

I am using `model-three` to render a 3D Model in a cordova application. It worked perfectly when I had the scene in my local assets. But when I try to load the scene from the server I get this error

>THREE.WebGLState: DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The image element contains cross-origin data, and may not be loaded.

My server has the response header `Access-Control-Allow-Origin "*"`. After some search I found, according to this [answer](https://stackoverflow.com/a/46461959/5107788), that setting the [crossOrigin](https://threejs.org/docs/#api/loaders/ObjectLoader.crossOrigin) might help.

Is there any way to do this through options? Do you have any other suggestion?

**Comment by odai-alali** [comment]
For the sake of experiment, I tried the following and the problem was solved.
```vue
<script>
  import { ObjectLoader } from 'three'
  import mixin from './model-mixin.vue'

  export default {
    name: 'model-three',
    mixins: [ mixin ],
    data () {
      return {
        loader: new ObjectLoader()
      }
    },
    created () {
      this.loader.setCrossOrigin('anonymous') // <-- here
    }
  }
</script>
```
Not sure if it should be hard coded in the component like this. An option should be provided for that.

**Comment by hujiulong** [comment]
Thanks for your feedback, I'll add a `crossOrigin` option.
