### ISSUE TITLE
小白 提问 如何使用下载后的文件

### ISSUE THREAD

**Issue by tttccc-design** [hujiulong/vue-3d-model#36]
请问大神， 我下载了大神上传的文件， 打开了example文件夹， 然后把demo里面HTML和js复制进去。还加载了Vue的cdn。想看见example做出来的事例，然后再upload自己的文件。可是我反复修改和尝试都无法在browser里显示出模型。Inspect 里面显示无法加载模型的文件。作为小白，还望大神讲解再详细一点。

**Comment by hujiulong** [comment]
什么格式的文件？具体的报错信息是什么？
