### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getAttribute' of undefined

### ISSUE THREAD

**Issue by batFormat** [hujiulong/vue-3d-model#39]
Uncaught TypeError: Cannot read property 'getAttribute' of undefined
![2018-05-10 5 16 31](https://user-images.githubusercontent.com/13119245/39848747-6743f75e-5411-11e8-91b3-d4c4f684f891.png)

In my component

```
<template>
    <div>
      <p>afaf</p>
      <model-collada :height="300" :width="600" src="public/avatar.dae"></model-collada>
    </div>
</template>

<script>
import { ModelCollada } from "vue-3d-model";

export default {
  components: {
    ModelCollada
  }
};
</script>
```

**Comment by hujiulong** [comment]
Have you tried other dae models?

**Comment by batFormat** [comment]
@hujiulong Please close, thanks a lot I solved this problem.
The reason was that I did not correctly point the way to the assets.
```
 <model-collada  src="./avatar.dae"></model-collada>
```
I use `vue-cli`.
My model files store in `public` folder
