### ISSUE TITLE
我在开发vue-threejs，希望可以交流学习

### ISSUE THREAD

**Issue by fritx** [hujiulong/vue-3d-model#4]
Hi，我最近也在重新启动vue-threejs的开发进程，
偶然在awesome-vue的WebGL模块发现这个作品，非常棒，
我觉得可以相互参考，多交流学习。

**Comment by hujiulong** [comment]
我以前看到过vue-threejs，没想到作者是国人，很高兴和你交流～
threejs对普通开发者还是有一定的学习难度，所以把vue和threejs或者WebGL结合起来，我感觉用处很大。我也计划再做几个和WebGL相关的组件

**Comment by fritx** [comment]
666，我近期可能也要准备一个有关vue-threejs的ppt，现在找到知己了，接下来我会抽空从这里学习。
相比起来，我对threejs的知识还比较有限，哈。

**Comment by hujiulong** [comment]
这也只是个简单的组件，还要继续完善。以后互相学习哈～

**Comment by hujiulong** [comment]
难得碰上兴趣一致的朋友，加个微信吧？ 我的微信iamjiulong

**Comment by fritx** [comment]
Nice！已加
