### ISSUE TITLE
改变模型贴图透明度

### ISSUE THREAD

**Issue by MonicaDan** [hujiulong/vue-3d-model#40]
你好请问，在导入了mtl文件的情况下，如何使用on-mousemove方法改变obj模型的亮度或者透明度？使得模型在鼠标过时产生一种高亮的状态。谢谢~

**Comment by hujiulong** [comment]
vue-3d-model目前是用three.js来渲染的，你可以从事件的参数中得到模型的object对象，然后就可以去控制它了，和three.js一样
