### ISSUE TITLE
使用vue组件时，报错

### ISSUE THREAD

**Issue by djymike** [hujiulong/vue-3d-model#41]
vue-3d-model.min.js?05bd:5 
Uncaught Error: OBJLoader: Unexpected line: "<!DOCTYPE html>"
    at r.parse (vue-3d-model.min.js?05bd:5)
    at Object.eval [as onLoad] (vue-3d-model.min.js?05bd:5)
    at XMLHttpRequest.eval (vue-3d-model.min.js?05bd:1)

请问该如何解决

**Comment by hujiulong** [comment]
这应该是解析模型出错了，换别的模型试试，确认下是不是模型的问题

**Comment by djymike** [comment]
模型没问题，有可能是路径的问题，换成json模型的时候，报错Can't parse ~assets/scene.json. Unexpected token < in JSON at position 0，
文件放在assets文件夹下，我的webpack路径设置'assets': path.resolve(__dirname, '../src/assets')，
所以文件的路径应该怎么写？

**Comment by hujiulong** [comment]
@djymike 模型应该放在static目录里，它不需要webpack去处理

**Comment by djymike** [comment]
可以了，感谢！

**Comment by heyouquan** [comment]
> 可以了，感谢！

想问一下你解决问题后的放置模型的static目录是怎么设置的呢？
