### ISSUE TITLE
.dae文件读取不了

### ISSUE THREAD

**Issue by djymike** [hujiulong/vue-3d-model#44]
obj和obj+mtl都能正常读取和显示，但dae不行，换了例子里几个dae都不行

**Comment by hujiulong** [comment]
有报错信息吗，在调试工具中看看模型是否加载了

**Comment by djymike** [comment]
现在dae能加载了，但旋转的中心点不是模型中心，在模型的脚下，用的你例子中的文件，obj正常的

**Comment by djymike** [comment]
这是打印信息
ColladaLoader: DOMParser: 10.62890625ms
vue-3d-model.min.js?02c2:5 ColladaLoader: File version 1.4.1
vue-3d-model.min.js?02c2:5 ColladaLoader: Parse: 67.755859375ms
vue-3d-model.min.js?02c2:5 ColladaLoader: Build: 131.046142578125ms
vue-3d-model.min.js?02c2:5 ColladaLoader: 211.123046875ms

**Comment by hujiulong** [comment]
@djymike 我测试了一下没有问题，具体是哪个模型呢?
