### ISSUE TITLE
这些model(json,obj)怎么生成啊？

### ISSUE THREAD

**Issue by hiwjcn** [hujiulong/vue-3d-model#45]
不要意思，我不太了解这个。
请教一下，如果我想对一个展品四周多拍几张照片怎么合成这个包可以读取的数据格式？

**Comment by hujiulong** [comment]
通过照片生成三维模型比较复杂，这个技术叫三维重建(3d reconstruction)

**Comment by hiwjcn** [comment]
@hujiulong 谢谢
