### ISSUE TITLE
报错THREE.WebGLRenderer 88

### ISSUE THREAD

**Issue by Carl2016** [hujiulong/vue-3d-model#46]
THREE.WebGLRenderer 88
vue-3d-model.min.js?05bd:5 Uncaught Error: OBJLoader: Unexpected line: "<!DOCTYPE html>"
    at r.parse (vue-3d-model.min.js?05bd:5)
    at Object.eval [as onLoad] (vue-3d-model.min.js?05bd:5)
    at XMLHttpRequest.eval (vue-3d-model.min.js?05bd:1)
parse @ vue-3d-model.min.js?05bd:5
(anonymous) @ vue-3d-model.min.js?05bd:5
(anonymous) @ vue-3d-model.min.js?05bd:1
XMLHttpRequest.send (async)
load @ vue-3d-model.min.js?05bd:1
load @ vue-3d-model.min.js?05bd:5
load @ vue-3d-model.min.js?05bd:5
mounted @ vue-3d-model.min.js?05bd:5
callHook @ vue.esm.js?efeb:2921
insert @ vue.esm.js?efeb:4158
invokeInsertHook @ vue.esm.js?efeb:5960
patch @ vue.esm.js?efeb:6179
Vue._update @ vue.esm.js?efeb:2660
updateComponent @ vue.esm.js?efeb:2788
get @ vue.esm.js?efeb:3142
Watcher @ vue.esm.js?efeb:3131
mountComponent @ vue.esm.js?efeb:2795
Vue.$mount @ vue.esm.js?efeb:8540
Vue.$mount @ vue.esm.js?efeb:10939
Vue._init @ vue.esm.js?efeb:4640
Vue @ vue.esm.js?efeb:4729
(anonymous) @ main.js?1c90:12
./src/main.js @ app.js:1085
__webpack_require__ @ app.js:679
fn @ app.js:89
0 @ app.js:1102
__webpack_require__ @ app.js:679
(anonymous) @ app.js:725
(anonymous) @ app.js:728

**Comment by hujiulong** [comment]
这是解析模型出错了，你看看模型是否正确加载了
