### ISSUE TITLE
Get dimensions of STL object?

### ISSUE THREAD

**Issue by jonbesga** [hujiulong/vue-3d-model#49]
Hi, is there any way to get the dimensions (x,y,z) of an STL object through the component?

**Comment by hujiulong** [comment]
what do you mean by the dimensions?

**Comment by jonbesga** [comment]
Width, Height, Depth of the object.

**Comment by hujiulong** [comment]
You can get the size through the following code
https://github.com/hujiulong/vue-3d-model/blob/e0468c0736a2db001e4a1c4a8747ed0c3bad4a32/src/util.js#L3-L10

**Comment by jonbesga** [comment]
Sorry, I forgot to mention that I'm trying to get the dimensions for a .stl object. It seems `getSize()` that is not available for the `model-stl` component. It's loaded only in the `model-obj` component

**Comment by hujiulong** [comment]
This library does not directly provide the `getSize` method. You need to modify the source code yourself or use three.js to do it.

I tried the model you provided, and I could get the size. 

code:
```vue
<template>
    <model-stl :backgroundAlpha="0"
        @on-load="onLoad"
        ref="model"
        src="static/a.stl"></model-stl>
</template>

<script>
import ModelStl from 'src/model-stl.vue'
import { getSize } from 'src/util'

export default {
    data() {
        return {};
    },
    methods: {
        onLoad() {
            const object = this.$refs.model.object;
            console.log( getSize( object ) );   // Vector3 {x: 40.75, y: 30.500001907348633, z: 30.5}
        }
    },
    components: {
        ModelStl
    }
}
</script>
```

**Comment by jonbesga** [comment]
Okay. The problem was that I was using the `getObject()` function which in the [model-stl.vue](https://github.com/hujiulong/vue-3d-model/blob/master/src/model-stl.vue) component has been overwritten and does not return simply the object, but generates an empty Mesh instead because no geometry parameter is passed.

Is this function in the STL component an expected behavior?

**Comment by hujiulong** [comment]
@jonbesga The method within the component is not provided to the external use, don't use `getObject()` and use `this.$refs.xx.object` to get object, just like my code above.
