### ISSUE TITLE
Load file from input type file?

### ISSUE THREAD

**Issue by mihamajetic** [hujiulong/vue-3d-model#55]
Hi, i just found your plugin and it's great! I am trying to use input file type for selecting STL file from my computer, but no success - because I cannot get file path. Can you help me with this one?

Error is _[Vue warn]: Invalid prop: type check failed for prop "src". Expected String, got File._

Here is my code:

HTML:
```
<input type="file" ref="stlFile" @change="changeStl">
<model-stl :src="srcStl">
```
JS:

```
new Vue({
    el: '#app',
    data: {
      srcStl : ""
    },
    methods: {
      changeStl() {
        const files = this.$refs.stlFile.files;
        console.log(files[0]);
        this.srcStl = files[0];
      }
    }
})
```
Thansk!

**Comment by hujiulong** [comment]
This way is not supported. If you have a certain understanding of three.js, you can look at [this file](https://github.com/mrdoob/three.js/blob/dev/editor/js/Loader.js).
