### ISSUE TITLE
get error with CDN

### ISSUE THREAD

**Issue by AndreySukhov** [hujiulong/vue-3d-model#56]
Hi

When following this url https://unpkg.com/vue-3d-model@1.0.2/dist/vue-3d-model.min.js can see this error ```Cannot find "/dist/vue-3d-model.min.js" in vue-3d-model@1.0.2```

**Comment by hujiulong** [comment]
Try this: https://unpkg.com/vue-3d-model@1.0.2/dist/vue-3d-model.js

**Comment by AndreySukhov** [comment]
that one worked, thanks
