### ISSUE TITLE
this.$ref.model.rotation

### ISSUE THREAD

**Issue by Steven520xiaowei** [hujiulong/vue-3d-model#58]
加载.obj的时候，好像这样获取到的rotation一直都x=0,y=0,z=0，是模型的问题吗

**Comment by Steven520xiaowei** [comment]
解决了。用this.$refs.model.camera.rotation就好了

**Comment by LucienXian** [comment]
@Steven520xiaowei 请问一下你是怎么设置camera的，我好像无论怎么改，都是看到同一个角度的模型
