### ISSUE TITLE
Add option to enable/disable gamma output on rederer

### ISSUE THREAD

**Issue by creazy231** [hujiulong/vue-3d-model#63]
@hujiulong I just have made some simple changes on the package to add the option to enable and disable gamma output on renderer. Could I get permission to push a new branch?

Thanks for the good work and that awesome 3d viewer.

**Comment by creazy231** [comment]
pull request opened 👍 
/close

**Comment by donmccurdy** [comment]
Note that `gammaOutput` should always be `true` for glTF models — it may be worth setting that as the default for the glTF component, if possible. See: https://threejs.org/docs/#examples/loaders/GLTFLoader.

**Comment by hujiulong** [comment]
@donmccurdy thanks, I have modified the code.

**Comment by donmccurdy** [comment]
Looks good! :)
