### ISSUE TITLE
Setting backgroundColor to transparent

### ISSUE THREAD

**Issue by viviendracon** [hujiulong/vue-3d-model#66]
I'm trying to set the background of the viewer to green.

I currently have this:
<model-obj src="../images/LeePerrySmith.obj" backgroundColor="#00ff00"></model-obj>

This isn't working. Could you please provide an example to do this correctly?

**Comment by viviendracon** [comment]
Hi @creazy231 I'm including the JS file. Thanks for replying.

**Comment by creazy231** [comment]
Had the same problem yesterday and figured out, that you have to divine the props of the Vue HTML Tag using lowercases.
Use `background-color` instead of `backgroundColor`

**Comment by viviendracon** [comment]
+10 @creazy231 I'll give this a try and update.

**Comment by creazy231** [comment]
Nice. Let me know if it worked 👍

**Comment by viviendracon** [comment]
Worked like a charm! Thanks!

**Comment by creazy231** [comment]
Awesome 👍🏻
I will add a merge request on Monday to update the examples
