### ISSUE TITLE
如何在代码里对模型进行一些实时操作

### ISSUE THREAD

**Issue by Axulai** [hujiulong/vue-3d-model#7]
如何在代码里对模型实时进行一些简单操作呢，如旋转平移缩放等，或者能否我预设定几个状态信息，然后提供一个方法，能够让我在合适的时候去切换

**Comment by Axulai** [comment]
比如我设定了几个state  在合适的时候我去触发  就可以了   在初始化的时候   我传进几个状态

**Comment by hujiulong** [comment]
看这个例子https://hujiulong.github.io/vue-3d-model/#/demo-rotate
可以传`roatation`,`position`,`scale`

**Comment by Axulai** [comment]
非常感谢  同时  我希望你可以在项目名称中加入three字样   因为很显然  目前three没有办法找到你这个很棒的项目！！

**Comment by 582252370** [comment]
大神，小白有两个问题:1、   <script src="vue.js"></script>  html代码里面这个在哪里呢? 

2、另外我下载了代码，做了一个html页面传到自己空间，打开确是空白，具体如下,百思不得其解，望指导：

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
</head>
<body>
    <div id="app">
        <model-obj src="http://www.xxxxx.com/3dtest/examples/static/models/obj/tree.obj"></model-obj>
    </div>
    <script src="../vue.js"></script>
    <script src="http://www.xxxxx.com/3dtest/dist/vue-3d-model.min.js"></script>
    <script>
        new Vue({
            el: '#app'
        })
    </script>
</body>

**Comment by hujiulong** [comment]
vue.js是一个前端框架，你可以在这里下载: https://cn.vuejs.org/v2/guide/installation.html
空白可能是因为你没有vue.js，另外如果你在本地调试，直接访问本地的模型文件会有跨域的问题，你需要弄个服务器环境，或者换成火狐浏览器

**Comment by Axulai** [comment]
更希望能够提供一个Render绑定，我们绑定一个方法，传进来一个对象信息，在three每次render的时候会执行到这个方法，而不是在loda事件中，去调用 requestAnimationFrame，同时，最好是把原生的对象抛出来, 让有能力的开发者可以对模型进行一些高端操作，比如贴图替换等等
 <model-collada
            :render="render"
            src="static/models/collada/elf.dae"></model-collada>

  methods: {
                render (obj) {
                    obj.position.x++;
                    obj.rotate.x++;
                    obj.rotate.y++;
                }
            }

最后还是很感谢这个项目！！如果可以，放个支付宝或微信付款码，我愿意请你喝一杯咖啡

**Comment by hujiulong** [comment]
可以这样去获取模型对象，一般来说会得到一个THREE.Group
```html
// template
<model-collada
    ref="model"
    on-load="onLoad"
    src="static/models/collada/elf.dae"></model-collada>
 
// script
methods: {
    onLoad () {
        const object = this.$refs.model.object;
        object.position.x = 100;
    }
}
```
也可以不在onLoad里操作，但是要注意在触发`on-load`之前，`this.$refs.model.object`的值都会是`null`

捐赠的话，等项目完善以后可能会加个二维码吧，以后再说。谢谢支持～
