### ISSUE TITLE
寻求帮助

### ISSUE THREAD

**Issue by huichenjun** [hujiulong/vue-3d-model#74]
您好，使用了您的demo但是报这个错   Offset is outside the bounds of the DataView 方便解答吗？

**Comment by hujiulong** [comment]
说明一下是什么格式的模型，错误最好截个图

**Comment by huichenjun** [comment]
您好，我使用的是stl模板文件

![default](https://user-images.githubusercontent.com/45968802/50193929-a96b1380-0373-11e9-9f40-7e30fa8bedb5.png)

报错就是这个，如果我用obj格式的话就报这个
![1](https://user-images.githubusercontent.com/45968802/50193934-aff98b00-0373-11e9-9e7d-bb09e08b2b6c.png)

比较小白，还请大神指点，项目明天就上线了，急死我了。方便的话能加个联系方式吗？这是我的qq3498738055

**Comment by huichenjun** [comment]
![image](https://user-images.githubusercontent.com/45968802/50193977-dc150c00-0373-11e9-898c-df9c0f7948fa.png)
![image](https://user-images.githubusercontent.com/45968802/50193988-e800ce00-0373-11e9-9568-734b9c69f94b.png)
![image](https://user-images.githubusercontent.com/45968802/50193996-ef27dc00-0373-11e9-9fc8-5e317226caa2.png)
这是我的代码，您看有哪里不对的吗？

**Comment by huichenjun** [comment]
您好，冒昧问下，现在方便解答下这个问题吗？？？？

**Comment by hujiulong** [comment]
那就是静态资源的地址没配好，和这个库没关系

**Comment by huichenjun** [comment]
我再次确认了一下，304状态码是未更新，首次请求的时候就是200成功状态，但是返回的内容为空，不知道是为什么，路径肯定是对的...也是放在static文件下面的.

**Comment by hujiulong** [comment]
你再确认下路由的处理吧，请求返回什么不是前端决定的

**Comment by huichenjun** [comment]
我用的是本地的文件，现在一直报这个
![image](https://user-images.githubusercontent.com/45968802/50215664-a6e1db80-03be-11e9-8767-13e5c2356125.png)
不知道怎么解决，项目是nuxt.js搭建的vue

**Comment by hujiulong** [comment]
就是因为没有请求到模型的数据呀，你看看是不是这个框架用serviceWorker拦截了请求，这些我也给不了你什么帮助

**Comment by huichenjun** [comment]
和我们的反向代理有关系吗？本地文件也请求不到吗？

**Comment by hujiulong** [comment]
和这个库没有关系，我先close掉这个问题了

**Comment by BenjaminWaye** [comment]
I created a completely new project using Vue CLI 3 and the issue is reproduceable, it seems to have to do with the way paths are handled in new webpack configuration. The img below works fine while model-stl can't find the src.
```
<model-stl src="../assets/stldemomodel.stl"></model-stl>
    <img alt="Vue logo" src="../assets/logo.png">
```

**Comment by hujiulong** [comment]
@BenjaminWaye @huichenjun You need to put models in the [public folder](https://cli.vuejs.org/guide/html-and-static-assets.html#the-public-folder), because vue-cli automatically changes the resource path in the assets directory.
