### ISSUE TITLE
黑色

### ISSUE THREAD

**Issue by huichenjun** [hujiulong/vue-3d-model#76]

**Comment by huichenjun** [comment]
模型背面是黑色的，这个可以去掉吗？
![image](https://user-images.githubusercontent.com/45968802/50334240-a1ad9980-0542-11e9-81ab-7b0adbfd30e4.png)
然后就是模型可以设置360无死角的旋转吗？现在拖动到一定角度就不能继续旋转了。感谢您的回复

**Comment by hujiulong** [comment]
lights 看这个 https://github.com/hujiulong/vue-3d-model/issues/26
