### ISSUE TITLE
json格式的数据是怎么获得的呢

### ISSUE THREAD

**Issue by hanxuelvzi** [hujiulong/vue-3d-model#8]
大神您好，我最近在研究3ds Max导出数据并且在浏览器上展示的问题，看了您的文章深受启发。vue目前支持obj、json、dae、stl四种格式的展示，在们的实验中发现obj与stl展示的时候是不带贴图的（obj有输出mtl文件不过似乎vue并没有去试图读取它）。而dae文件输出与其他几种格式相比非常大，同一份数据输出其他的只有几M，而dae文件达到了几百M，这使得浏览器读取十分缓慢。最后我们选择json格式。我们下载three.js的插件安装到blender中，导入dae数据并导出json格式，但是放到浏览器上后，浏览器提示我们的数据缺少了一些信息。与您的json数据比较后，发现较您的数据确实少了很多信息。我想请教大神，您的json数据是怎么获得的呢？如果也是使用blender输出的话，是用什么数据导入的呢？问题比较长，能看到这里十分感谢~

**Comment by hanxuelvzi** [comment]
现在使用我们输出的json格式可以在浏览器上展示模型，在F12中的Network也可以看到浏览器确实获取了贴图的信息，但是依然不显示，究竟是什么原因呢？

**Comment by Axulai** [comment]
模型问题请去直接查找关于three.js的相关知识，这里插件只是对three的一个简单封装

**Comment by hujiulong** [comment]
这里有将obj文件转成json的脚本 https://github.com/mrdoob/three.js/tree/dev/utils/converters

**Comment by hujiulong** [comment]
听描述也不好定位问题，最好在jsfiddle之类的地方写个在线DEMO

**Comment by hanxuelvzi** [comment]
谢谢大神~我们最后还是选择了用three.js去读取3ds Max导出的obj文件，问题已经解决啦~这个帖子还是帮到了很多，再次谢谢大神
