### ISSUE TITLE
可以在一个建模里面互动吗？

### ISSUE THREAD

**Issue by qiqilie** [hujiulong/vue-3d-model#90]
请问可以在一个建模中触发不同区域块的触发方法吗？点击不同区块可以触发效果，或者赋值

**Comment by wuafan** [comment]
能不能实现在模型的相关位置展示相关的实时数据标签

**Comment by hujiulong** [comment]
可以通过onClick中获得的信息来判断点击的区域
看[这个例子](https://hujiulong.github.io/vue-3d-model/#/demo-event)中控制台打印的数据
