### ISSUE TITLE
添加进度条

### ISSUE THREAD

**Issue by caoxiaofei3** [hujiulong/vue-3d-model#95]
模型过于大，加载速度比较慢，希望添加进度条

**Comment by hujiulong** [comment]
可以通过监听`on-progress`，`on-load`，`on-error`来实现。
在初始时展示进度条，通过监听`on-progress`来获取数据更新进度条，在`on-load`或`on-error`时移除进度条

**Comment by caoxiaofei3** [comment]
谢谢
